import { getSession } from 'next-auth/client'
import Head from 'next/head'
import Header from './component/Header'
import MainPage from './component/MainPage'
import Login from './Login'

export default function Home({session}) {
  if(!session) return <Login />

  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-facebook.png" />
      </Head>

      <main className="h-screen overflow-hidden">
        <Header />
        <MainPage />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  return {
    props: {
      session
    }, // will be passed to the page component as props
  }
}
